default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: verbier_development

test:
  <<: *default
  database: verbier_test

production:
  <<: *default
  database: verbier_production
